<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFrameworks>net8.0;net9.0;net10.0</TargetFrameworks>
    <NoWarn>$(NoWarn);CS1591</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <None Update="appsettings.Test.json" CopyToOutputDirectory="Always" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="xunit.v3" />
    <PackageReference Include="Microsoft.Testing.Extensions.CodeCoverage" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CasCap.Api.Azure.Storage\CasCap.Api.Azure.Storage.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" />
  </ItemGroup>

  <Choose>
    <When Condition="'$(Configuration)'=='Debug'">
      <ItemGroup>
		<ProjectReference Include="..\..\..\CasCap.Common\src\CasCap.Common.Logging\CasCap.Common.Logging.csproj" />
        <ProjectReference Include="..\..\..\CasCap.Common\src\CasCap.Common.Testing\CasCap.Common.Testing.csproj" />
      </ItemGroup>
    </When>
    <Otherwise>
      <ItemGroup>
		<PackageReference Include="CasCap.Common.Logging" />
        <PackageReference Include="CasCap.Common.Testing" />
      </ItemGroup>
    </Otherwise>
  </Choose>
</Project>
