services:

  #https://github.com/azure/azurite
  azurite:
    image: mcr.microsoft.com/azure-storage/azurite #formerly arafato/azurite
    #--skipApiVersionCheck: the Azure Storage SDK can send a newer x-ms-version than the latest Azurite image supports.
    command: azurite --blobHost 0.0.0.0 --queueHost 0.0.0.0 --tableHost 0.0.0.0 --skipApiVersionCheck --location /data
    volumes:
      - ./.docker/azurite:/data
    ports:
      #- https://github.com/docker/for-win/issues/3171#issuecomment-554587817
      - 10000:10000 #blob
      - 10001:10001 #queue
      - 10002:10002 #table
